name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Compile and link native library'
        run: |
          cc --version
          cc -shared -o libhelloworld.so demo/native/helloworld.c
      - name: 'Set up jextract'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: jextract
      - name: 'Set up Java'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: GA
      - name: 'Build and run demo'
        run: |
          java --show-version .bach/src/Build.java
